import './globals.css'
import { JetBrains_Mono } from '@next/font/google'

const jetBrainsMono = JetBrains_Mono({
	weight: ['400', '700'],
	subsets: ['cyrillic'],
	variable: '--font-jetBrainsMono'
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${jetBrainsMono.className}`}>{children}</body>
		</html>
	)
}
